name: Deploy Backend to EC2

on:
  push:
    branches: [ main, master ]
    paths:
      - 'backend/**'
      - 'scripts/**'
      - '.github/workflows/**'
      - 'requirements.txt'
      - 'Procfile'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        cd backend
        python manage.py check
        python manage.py migrate --check

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy Backend to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          cd /var/www/workshop-platform-backend
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          cd backend
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart workshop-backend
          sudo systemctl restart nginx
          
    - name: Health Check
      run: |
        sleep 30
        curl -f ${{ secrets.BACKEND_URL }}/api/ || exit 1
        script: |
          # Navigate to project directory
          cd /home/ubuntu/workshop-platform-backend
          
          # Pull latest changes
          git pull origin main
          
          # Activate virtual environment
          source venv/bin/activate
          
          # Install/update dependencies
          cd backend
          pip install -r requirements.txt
          
          # Run migrations
          python manage.py migrate
          
          # Collect static files
          python manage.py collectstatic --noinput
          
          # Restart services
          sudo systemctl restart workshop-platform-backend
          sudo systemctl restart nginx