name: Deploy Backend to EC2

on:
  push:
    branches: [ main, master ]
    paths:
      - 'backend/**'
      - 'scripts/**'
      - '.github/workflows/**'
      - 'requirements.txt'
      - 'Procfile'
concurrency:
    group: main-deploy
    cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        cd backend
        python manage.py check
        python manage.py migrate --check

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy Backend to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          cd /var/www/workshop-platform-backend
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          cd backend
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo supervisorctl restart workshop-platform-backend
          sudo systemctl reload nginx
          
    - name: Health Check
      run: |
        sleep 30
        curl -f ${{ secrets.BACKEND_URL }}/api/ || exit 1
        
    - name: Deployment Success Notification
      if: success()
      run: echo "✅ Backend deployment completed successfully!"
      
    - name: Deployment Failure Notification
      if: failure()
      run: echo "❌ Backend deployment failed!"